global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # SQL Genius AI Application
  - job_name: 'sql-genius-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # SQL Genius AI Workers
  - job_name: 'sql-genius-workers'
    static_configs:
      - targets: ['worker-1:8001', 'worker-2:8001', 'worker-3:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # AWS CloudWatch (via CloudWatch Exporter)
  - job_name: 'cloudwatch'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
    scrape_interval: 60s
    metrics_path: '/metrics'
    params:
      region: ['us-east-1']

  # Blackbox Exporter (External Monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.sqlgenius.ai/health
        - https://app.sqlgenius.ai
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Jaeger Tracing
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    scrape_interval: 30s

  # Elasticsearch (ELK Stack)
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: '/_prometheus/metrics'

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['business-metrics-exporter:8080']
    scrape_interval: 60s

  # AI API Cost Tracking
  - job_name: 'ai-cost-tracker'
    static_configs:
      - targets: ['ai-cost-tracker:8080']
    scrape_interval: 300s  # 5 minutes

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.monitoring.sqlgenius.ai/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500